# Generated by Django 5.1.3 on 2025-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha ')),
                ('author', models.CharField(max_length=500, verbose_name='Muallif ')),
                ('image', models.ImageField(upload_to='media/kutubxona/', verbose_name='Fotosurat ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Kutubxona',
            },
        ),
    ]
