# Generated by Django 5.2.3 on 2025-07-12 21:58

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=155, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('card_image', models.ImageField(blank=True, help_text='Image displayed on the news card.', null=True, upload_to='news_card_images/', verbose_name='Card Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the news item was created.', verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
