# Generated by Django 5.1.3 on 2025-07-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tadbirlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha ')),
                ('place', models.CharField(max_length=250, verbose_name="O'tkaziladigan joyi")),
                ('date', models.DateTimeField(verbose_name="Tadbir o'tkaziladigan vaqti")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Tadbirlar',
            },
        ),
    ]
