# Generated by Django 5.1.3 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Elon uchun sarlavha: ')),
                ('description', models.CharField(max_length=500, verbose_name="Elon haqida ma'lumot: ")),
                ('image', models.ImageField(upload_to='media/elonlar/', verbose_name='Elon uchun fotosurat: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Elonlar',
            },
        ),
    ]
