# Generated by Django 5.2.3 on 2025-07-12 21:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elonlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=155, unique=True, verbose_name='Elon uchun slug')),
                ('title', models.CharField(max_length=500, verbose_name='Elon uchun sarlavha')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Elon haqida malumot')),
                ('image', models.ImageField(upload_to='media/elonlar/', verbose_name='Elon uchun fotosurat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Elonlar',
            },
        ),
    ]
