# Generated by Django 5.2.3 on 2025-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonlar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elonlar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='elonlar',
            name='slug',
        ),
        migrations.AlterField(
            model_name='elonlar',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description '),
        ),
        migrations.AlterField(
            model_name='elonlar',
            name='image',
            field=models.ImageField(upload_to='media/kutubxona/', verbose_name='Fotosurat '),
        ),
        migrations.AlterField(
            model_name='elonlar',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Sarlavha '),
        ),
    ]
