# Generated by Django 5.1.3 on 2025-07-02 17:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elonlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elonlar',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Elon haqida malumot '),
        ),
        migrations.AlterField(
            model_name='elonlar',
            name='image',
            field=models.ImageField(upload_to='media/elonlar/', verbose_name='Elon uchun fotosurat '),
        ),
        migrations.AlterField(
            model_name='elonlar',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Elon uchun sarlavha '),
        ),
    ]
