# Generated by Django 5.1.3 on 2025-07-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=500, verbose_name="Hodimning to'liq ismi: ")),
                ('image', models.ImageField(upload_to='', verbose_name='Hodimning fotosurati: ')),
                ('lavozimi', models.CharField(max_length=500, verbose_name='Hodimning lavozimi: ')),
                ('phone', models.CharField(max_length=500, verbose_name='Hodimning telefon raqami: ')),
                ('telegram', models.CharField(max_length=500, verbose_name='Hodimning telegram raqami: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Hodimlar',
            },
        ),
    ]
