# Generated by Django 5.1.3 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodimlar',
            name='image',
            field=models.ImageField(upload_to='media/hodimlar/', verbose_name='Hodimning fotosurati: '),
        ),
    ]
